-- MySQL Script generated by MySQL Workbench
-- Wed Oct 18 09:37:50 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Hotel
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Hotel` ;

-- -----------------------------------------------------
-- Schema Hotel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Hotel` DEFAULT CHARACTER SET utf8 ;
USE `Hotel` ;

-- -----------------------------------------------------
-- Table `Hotel`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hotel`.`cliente` (
  `documento` VARCHAR(12) NOT NULL,
  `tipoDocumento` VARCHAR(2) NOT NULL,
  `nombre` VARCHAR(50) NULL,
  `ciudad` VARCHAR(15) NULL,
  `pais` VARCHAR(20) NULL,
  PRIMARY KEY (`documento`, `tipoDocumento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hotel`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hotel`.`empleado` (
  `tipoDocumento` VARCHAR(2) NOT NULL,
  `documento` VARCHAR(12) NOT NULL,
  `cargo` ENUM('Administrador', 'Director', 'Recepcionista', 'Botones', 'Camarero', 'Cocinero') NULL,
  PRIMARY KEY (`tipoDocumento`, `documento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hotel`.`torre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hotel`.`torre` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `nroHabitaciones` VARCHAR(4) NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hotel`.`habitacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hotel`.`habitacion` (
  `idHabitacion` VARCHAR(4) NOT NULL,
  `idTorre` INT NULL,
  PRIMARY KEY (`idHabitacion`),
  CONSTRAINT `idTorre`
    FOREIGN KEY (`idTorre`)
    REFERENCES `Hotel`.`torre` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `idTorre_idx` ON `Hotel`.`habitacion` (`idTorre` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Hotel`.`reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hotel`.`reserva` (
  `idReserva` VARCHAR(10) NOT NULL,
  `idCliente` VARCHAR(15) NULL,
  `idHabitacion` VARCHAR(4) NULL,
  `tipoDocumentoEmpleado` VARCHAR(2) NULL,
  `idDocumentoEmpleado` VARCHAR(12) NULL,
  `fecha_de_reserva` DATETIME NULL,
  `fechaIngreso` DATETIME NULL,
  `fechaSalida` DATETIME NULL,
  `estado` ENUM('Cancelada', 'Tomada', 'Aplazada') NULL,
  PRIMARY KEY (`idReserva`),
  CONSTRAINT `idCliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `Hotel`.`cliente` (`documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idHabitacion`
    FOREIGN KEY (`idHabitacion`)
    REFERENCES `Hotel`.`habitacion` (`idHabitacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tipoDocumentoEmpleado`
    FOREIGN KEY (`tipoDocumentoEmpleado`)
    REFERENCES `Hotel`.`empleado` (`tipoDocumento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idDocumentoEmpleado`
    FOREIGN KEY (`idDocumentoEmpleado`)
    REFERENCES `Hotel`.`empleado` (`documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `idCliente_idx` ON `Hotel`.`reserva` (`idCliente` ASC) VISIBLE;

CREATE INDEX `idHabitacion_idx` ON `Hotel`.`reserva` (`idHabitacion` ASC) VISIBLE;

CREATE INDEX `tipoDocumentoEmpleado_idx` ON `Hotel`.`reserva` (`tipoDocumentoEmpleado` ASC) VISIBLE;

CREATE INDEX `idDocumentoEmpleado_idx` ON `Hotel`.`reserva` (`idDocumentoEmpleado` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
